name: Docker Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu:20.04

    steps:
    - uses: actions/checkout@v3
    - name: Docker build
      run: docker build -t my-app:1.0
      
