name: Docker test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu:18.04 

    steps:
    - uses: actions/checkout@v3
    - name: Docker build
      run: docker build -t my-app:1.0
      
